const tablaClasificacion = [
    {
      puesto: 1,
      equipo: "R. Madrid",
      puntos: 28,
      partidosJugados: 11,
      partidosGanados: 9,
      partidosEmpatados: 1,
      partidosPerdidos: 1,
      golesAFavor: 23,
      golesEnContra: 8,
    },
    {
      puesto: 2,
      equipo: "Girona",
      puntos: 28,
      partidosJugados: 11,
      partidosGanados: 9,
      partidosEmpatados: 1,
      partidosPerdidos: 1,
      golesAFavor: 25,
      golesEnContra: 13,
    },
    {
      puesto: 3,
      equipo: "Atlético",
      puntos: 25,
      partidosJugados: 10,
      partidosGanados: 8,
      partidosEmpatados: 1,
      partidosPerdidos: 1,
      golesAFavor: 25,
      golesEnContra: 9,
    },
    {
      puesto: 4,
      equipo: "Barcelona",
      puntos: 24,
      partidosJugados: 11,
      partidosGanados: 7,
      partidosEmpatados: 3,
      partidosPerdidos: 1,
      golesAFavor: 23,
      golesEnContra: 12,
    },
    {
      puesto: 5,
      equipo: "R. Sociedad",
      puntos: 19,
      partidosJugados: 11,
      partidosGanados: 5,
      partidosEmpatados: 4,
      partidosPerdidos: 2,
      golesAFavor: 20,
      golesEnContra: 14,
    },
    {
      puesto: 6,
      equipo: "Athletic",
      puntos: 18,
      partidosJugados: 11,
      partidosGanados: 5,
      partidosEmpatados: 3,
      partidosPerdidos: 3,
      golesAFavor: 18,
      golesEnContra: 12,
    },
    {
      puesto: 7,
      equipo: "Betis",
      puntos: 17,
      partidosJugados: 11,
      partidosGanados: 4,
      partidosEmpatados: 5,
      partidosPerdidos: 2,
      golesAFavor: 14,
      golesEnContra: 15,
    },
    {
      puesto: 8,
      equipo: "Rayo",
      puntos: 17,
      partidosJugados: 11,
      partidosGanados: 4,
      partidosEmpatados: 5,
      partidosPerdidos: 2,
      golesAFavor: 14,
      golesEnContra: 15,
    },
    {
      puesto: 9,
      equipo: "Valencia",
      puntos: 15,
      partidosJugados: 11,
      partidosGanados: 4,
      partidosEmpatados: 3,
      partidosPerdidos: 4,
      golesAFavor: 14,
      golesEnContra: 13,
    },
    {
      puesto: 10,
      equipo: "Las Palmas",
      puntos: 14,
      partidosJugados: 11,
      partidosGanados: 4,
      partidosEmpatados: 2,
      partidosPerdidos: 5,
      golesAFavor: 8,
      golesEnContra: 10,
    },
    {
      puesto: 11,
      equipo: "Osasuna",
      puntos: 13,
      partidosJugados: 11,
      partidosGanados: 4,
      partidosEmpatados: 1,
      partidosPerdidos: 6,
      golesAFavor: 12,
      golesEnContra: 16,
    },
    {
      puesto: 12,
      equipo: "Getafe",
      puntos: 12,
      partidosJugados: 11,
      partidosGanados: 2,
      partidosEmpatados: 6,
      partidosPerdidos: 3,
      golesAFavor: 13,
      golesEnContra: 16,
    },
    {
      puesto: 13,
      equipo: "Sevilla",
      puntos: 10,
      partidosJugados: 10,
      partidosGanados: 2,
      partidosEmpatados: 4,
      partidosPerdidos: 4,
      golesAFavor: 16,
      golesEnContra: 15,
    },
    {
      puesto: 14,
      equipo: "Cádiz",
      puntos: 10,
      partidosJugados: 11,
      partidosGanados: 2,
      partidosEmpatados: 4,
      partidosPerdidos: 5,
      golesAFavor: 10,
      golesEnContra: 16,
    },
    {
      puesto: 15,
      equipo: "Mallorca",
      puntos: 9,
      partidosJugados: 11,
      partidosGanados: 1,
      partidosEmpatados: 6,
      partidosPerdidos: 4,
      golesAFavor: 12,
      golesEnContra: 16,
    },
    {
      puesto: 16,
      equipo: "Villarreal",
      puntos: 9,
      partidosJugados: 10,
      partidosGanados: 2,
      partidosEmpatados: 3,
      partidosPerdidos: 5,
      golesAFavor: 12,
      golesEnContra: 16,
    },
    {
      puesto: 17,
      equipo: "Alavés",
      puntos: 9,
      partidosJugados: 11,
      partidosGanados: 2,
      partidosEmpatados: 3,
      partidosPerdidos: 6,
      golesAFavor: 9,
      golesEnContra: 16,
    },
    {
      puesto: 18,
      equipo: "Celta",
      puntos: 6,
      partidosJugados: 11,
      partidosGanados: 1,
      partidosEmpatados: 3,
      partidosPerdidos: 7,
      golesAFavor: 10,
      golesEnContra: 19,
    },
    {
      puesto: 19,
      equipo: "Granada",
      puntos: 6,
      partidosJugados: 10,
      partidosGanados: 1,
      partidosEmpatados: 3,
      partidosPerdidos: 6,
      golesAFavor: 15,
      golesEnContra: 25,
    },
    {
      puesto: 20,
      equipo: "Almería",
      puntos: 3,
      partidosJugados: 11,
      partidosGanados: 0,
      partidosEmpatados: 3,
      partidosPerdidos: 8,
      golesAFavor: 14,
      golesEnContra: 31,
    },
  ];
  
  function darEquipo(nombreEquipo) {
    const equipo = tablaClasificacion.find((equipo) => equipo.equipo === nombreEquipo);
    
    if (equipo) {
      document.write(`Resultados para el equipo ${equipo.equipo}: <br>`);
      document.write(`Puesto: ${equipo.puesto} <br>`);
      document.write(`Puntos: ${equipo.puntos} <br>`);
      document.write(`Partidos Jugados: ${equipo.partidosJugados} <br>`);
      document.write(`Partidos Ganados: ${equipo.partidosGanados} <br>`);
      document.write(`Partidos Empatados: ${equipo.partidosEmpatados} <br>`);
      document.write(`Partidos Perdidos: ${equipo.partidosPerdidos} <br>`);
      document.write(`Goles a Favor: ${equipo.golesAFavor} <br>`);
      document.write(`Goles en Contra: ${equipo.golesEnContra} <br>`);
    } else {
      document.write(`El equipo ${nombreEquipo} no se encuentra en la tabla de clasificación. <br>`);
    }
  }

  // Probamos con el equipo Almería
  darEquipo("Almería");